// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAt_8B5HPN8WzBclwdci_Z-cq5OXUKRGnw',
    appId: '1:525574477747:web:246adff73788c023499dc6',
    messagingSenderId: '525574477747',
    projectId: 'schoolmis-d436a',
    authDomain: 'schoolmis-d436a.firebaseapp.com',
    storageBucket: 'schoolmis-d436a.firebasestorage.app',
    measurementId: 'G-0W5D9QB06J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAokbzZE5mlKFB1PMObXSzuPaut74W3OaM',
    appId: '1:525574477747:android:0df2b533416de439499dc6',
    messagingSenderId: '525574477747',
    projectId: 'schoolmis-d436a',
    storageBucket: 'schoolmis-d436a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1-iEyOKusr_-WyK8i1z2sFqTK9-QScbU',
    appId: '1:525574477747:ios:c78e92a2f0fb00f0499dc6',
    messagingSenderId: '525574477747',
    projectId: 'schoolmis-d436a',
    storageBucket: 'schoolmis-d436a.firebasestorage.app',
    iosBundleId: 'com.example.schoolMis',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1-iEyOKusr_-WyK8i1z2sFqTK9-QScbU',
    appId: '1:525574477747:ios:c78e92a2f0fb00f0499dc6',
    messagingSenderId: '525574477747',
    projectId: 'schoolmis-d436a',
    storageBucket: 'schoolmis-d436a.firebasestorage.app',
    iosBundleId: 'com.example.schoolMis',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAt_8B5HPN8WzBclwdci_Z-cq5OXUKRGnw',
    appId: '1:525574477747:web:35646a2276982564499dc6',
    messagingSenderId: '525574477747',
    projectId: 'schoolmis-d436a',
    authDomain: 'schoolmis-d436a.firebaseapp.com',
    storageBucket: 'schoolmis-d436a.firebasestorage.app',
    measurementId: 'G-0LGYHB95T2',
  );
}
